### ISSUE TITLE
网络调试助手TCP客户端模式下不支持自选本地网卡

### ISSUE THREAD

**Issue by weycen** [feiyangqingyun/QWidgetDemo#30]
在TCP client模式下, 不支持选择'本地主机地址', 在多网卡下是socket自动选择网卡吧, 应该增加手动选择'本地主机地址'(socket显式绑定网卡)的功能, 否则多网卡下没法确定是当前软件选择的到底是哪个网卡

**Comment by feiyangqingyun** [comment]
tcpserver模块有下拉选择网卡的，tcpclient只需要连接服务器就行，没有选择网卡的说法



在 2021-08-10 14:40:06，"Chengwei Qiu" ***@***.***> 写道：

在TCP client模式下, 不支持选择'本地主机地址', 在多网卡下是socket自动选择网卡吧, 应该增加手动选择'本地主机地址'(socket显式绑定网卡)的功能, 否则多网卡下没法确定是当前软件选择的到底是哪个网卡

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by weycen** [comment]
某些场景下是需要手动选择网卡的: 当电脑接有多个不同IP的USB网卡，我连接到服务器(此时的服务器可能是绑定到本机的另一个网卡, 或者是公网的主机， 也或者是局域网内别的主机)时想要指定某一个网卡来连接, 这个时候如果不显式选择的话，socket自动选择的很可能不是我想要的网卡, 有时候一台电脑多个USB网卡能实现的调试场景, 如果不能在TCP Client端指定网卡, 可能要多台电脑才能实现
